-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT OUTER JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL;

-- NOT IN 으로 푼 사람도 많음
SELECT
ANIMAL_ID, NAME
FROM ANIMAL_OUTS O
WHERE O.ANIMAL_ID NOT IN (
SELECT ANIMAL_ID from ANIMAL_INS);